#!/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &
~/bin/xrandr_config.sh
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config focused_border_color "#f38ba8"
bspc config border_width 3

bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true

# Autostart
~/.fehbg
~/bin/xrandr_config.sh
# picom --config ~/.config/picom/picom.conf
~/.config/polybar/launch.sh
nm-applet &
$HOME/git/kaze/dist/KAze &
