#! /bin/sh


bspc monitor -d I II III IV V VI VII VIII IX X

// common options
bspc config border_width         4
bspc config window_gap          18
bspc config top_padding			40 
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a nm-connection-editor state=floating
bspc rule -a '*:Zathura' state=tiled
// start programs
dunst &
picom -b -d :0 &
$HOME/.config/polybar/launch.sh &
$HOME/.fehbg &
sxhkd &
fcitx -d &
